import Head from 'next/head'
import Image from 'next/image'
import {
  Navigation,
  AboutSection,
  GallerySection,
  OrderSection
} from '../components'
import logoPic from '../public/logo.svg'
import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cookies by Coffey</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.svg' />
      </Head>
      <Navigation />
      {/* TODO: add image optimization */}
      <header className="flex items-center justify-center bg-[url('/header.jpg')] bg-cover h-[50vh]">
        <div className='flex justify-center w-[85vw] md:w-[55vw] lg:w-[40vw] max-h-80 overflow-hidden bg-white bg-opacity-75 rounded-md'>
          <Image src={logoPic} alt='Logo' />
        </div>
      </header>
      <main className='grid gap-8 p-4 lg:py-8 lg:px-24 xl:px-48 lg:grid-cols-2'>
        <AboutSection />
        <GallerySection />
        <OrderSection className='lg:col-span-2' />
      </main>
    </>
  )
}

export default Home
