import Head from 'next/head'
import {
  Navigation,
  AboutSection,
  GallerySection,
  OrderSection
} from '../components'
import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cookies by Coffey</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      {/* TODO: add image optimization */}
      <header className="flex items-center justify-center bg-[url('/header.jpg')] bg-cover h-[50vh]">
        <h1 className='p-4 text-4xl rounded-md font-extralight bg-primary'>
          Cookies by Coffey
        </h1>
      </header>
      <main>
        <AboutSection />
        <GallerySection />
        <OrderSection />
      </main>
    </>
  )
}

export default Home
